basePath: /
consumes:
- application/json
definitions:
  Log:
    properties:
      created_on:
        type: string
        x-go-name: CreatedOn
      description:
        type: string
        x-go-name: Description
      id:
        format: int64
        type: integer
        x-go-name: ID
      type:
        description: the type for this user
        type: string
        x-go-name: Type
    required:
    - type
    type: object
    x-go-package: github.com/JungBin-Eom/OpenStack-Logger/data
info:
  description: Documentation for OpenStack VM Logger API
  title: of Logger API
  version: 1.0.0
paths:
  /:
    get:
      description: Retruns a list of Logs
      operationId: listLogs
      responses:
        "200":
          $ref: '#/responses/logsResponse'
      tags:
      - logs
produces:
- application/json
responses:
  logsResponse:
    description: A list of logs returns in the response
    schema:
      items:
        $ref: '#/definitions/Log'
      type: array
schemes:
- http
swagger: "2.0"
